/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://et6cnyv22bd7rjuaqyvj27pyue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ymxtbzv4mvbwripz7rrnzx35gu",
    "aws_cognito_identity_pool_id": "us-east-1:724be05d-ae7f-4f54-bb08-b76bd0ed1c4f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NxmL8Tc9r",
    "aws_user_pools_web_client_id": "1uocj5cbi2ql9dt03ni12v684",
    "oauth": {
        "domain": "4n77dm77rbzc-rage.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://10.253.157.75:19000,exp+rage://expo-development-client/?url=http%3A%2F%2F10.253.157.75%3A8081,exp+rage://expo-development-client/,rage://",
        "redirectSignOut": "exp://10.253.157.75:19000,exp+rage://expo-development-client/?url=http%3A%2F%2F10.253.157.75%3A8081,exp+rage://expo-development-client/,rage://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rage-storage-3172b28d235352-rage",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
