export const OpenFoodFactsCategories = {
    "en:dietary-supplements": "Dietary Supplements",
    "en:plant-based-foods-and-beverages": "Vegetables and Vegetable Products",
    "en:snacks": "Snacks",
    "en:beverages": "Drinks",
    "en:meals": "Meals, Entrees, and Side Dishes",
    "en:meats-and-their-products": "Meals, Entrees, and Side Dishes",
    "en:condiments": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:frozen-foods": "Frozen Food",
    "en:breakfasts": "Meals, Entrees, and Side Dishes",
    "en:sandwiches": "Meals, Entrees, and Side Dishes",
    "en:salads": "Vegetables and Vegetable Products",
    "en:canned-foods": "Canned Food",
    "en:powdered-creamer": "Dairy and Egg Products",
    "en:dairies": "Dairy and Egg Products",
    "en:sweet-pies": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:crepes-and-galettes": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:croquette": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:seafood": "Finfish and Shellfish Products",
    "en:cocoa-and-its-products": "Snack, Energy & Granola Bars",
    "en:ready-to-bake": "Breads & Buns",
    "en:sweeteners": "Confectionery Products",
    "en:100-juice": "Drinks",
    "en:dry-lentils": "Legumes and Legume Products",
    "en:cooking-helpers": "Branded Food Products Database",
    "en:farming-products": "Branded Food Products Database",
    "en:pies": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:desserts": "Confectionery Products",
    "en:beverages-and-beverages-preparations": "Drinks",
    "en:herb-tea": "Drinks",
    "en:iced-tea-with-blackberry-flavor": "Drinks",
    "en:bread-coverings": "Jam, Jelly & Fruit Spreads",
    "en:spreads": "Jam, Jelly & Fruit Spreads",
    "en:stuffing": "Breads & Buns",
    "en:instant-coffee-mix": "Coffee",
    "en:ribbon-noodles": "Pasta by Shape & Type",
    "en:breakfast-bars": "Breakfast Cereals",
    "en:bison": "Lamb, Veal, and Game Products",
    "en:cucumbers-in-brine": "Vegetables and Vegetable Products",
    "en:meat-snacks": "Other Meats",
    "en:meat-alternatives": "Other Meats",
    "en:food-additives": "Branded Food Products Database",
    "en:vegan-meatballs": "Other Meats",
    "en:snacks-snacks-sucres-barres-barres-de-cereales-collation": "Breakfast Cereals",
    "en:balsamic-vinaigrette-dressing": "Seasoning Mixes, Salts, Marinades & Tenderizers",
    "en:chips-and-fries": "Potato",
    "en:cheese-sauce-mix": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:chocolate-covered-coffee-beans": "Chocolate",
    "en:cheese-cracker": "Snacks",
    "en:soymilk": "Drinks",
    "en:microwavable-popcorn": "Popcorn, Peanuts, Seeds & Related Snacks",
    "en:fats": "Fats and Oils",
    "en:whole-grains": "Breads & Buns",
    "en:baking-decorations": "Confectionery Products",
    "en:snacks-salty-snacks-appetizers-crackers": "Chips, Pretzels & Snacks",
    "en:mixed-nuts": "Popcorn, Peanuts, Seeds & Related Snacks",
    "en:frozen-noodles": "Prepared Pasta & Pizza Sauces",
    "en:vegan": "Vegetables and Vegetable Products",
    "en:specific-products": "Branded Food Products Database",
    "en:candy-snack": "Confectionery Products",
    "en:gummy-candy": "Confectionery Products",
    "en:grits": "Cereal Grains and Pasta",
    "en:parmesan-cheese": "Dairy and Egg Products",
    "en:caramel-dessert-topping": "Confectionery Products",
    "en:vegetable-sushi": "Finfish and Shellfish Products",
    "en:flour-tortillas": "Breads & Buns",
    "en:canned-precooked-meat": "Canned Meat",
    "en:cheese-powder": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:salted-snacks": "Other Snacks",
    "en:black-tiger-prawns-in-marie-rose-dip": "Finfish and Shellfish Products",
    "en:beans": "Legumes and Legume Products",
    "en:sourdough": "Breads & Buns",
    "en:take-home-meal": "Meals, Entrees, and Side Dishes",
    "en:cornbread": "Breads & Buns",
    "en:freeze-dried-foods": "Frozen Food",
    "en:freeze-dried": "Frozen Food",
    "en:trail-mix": "Popcorn, Peanuts, Seeds & Related Snacks",
    "en:dried-products": "Popcorn, Peanuts, Seeds & Related Snacks",
    "en:fried-foods": "Fast Foods",
    "en:dried-dates": "Fruits and Fruit Juices",
    "en:dairy-free-cheese": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:fruit-cocktail": "Fruits and Fruit Juices",
    "en:condensed-soup": "Soups, Sauces, and Gravies",
    "en:canned-peach-in-heavy-syrup": "Fruits and Fruit Juices",
    "en:spaghetti-sauce": "Canned Food",
    "en:flavored-coconut-water": "Water",
    "en:stuffed-grape-leaves": "Fruits and Fruit Juices",
    "en:dessert-a-la-gelatine": "Fruits and Fruit Juices",
    "en:spices-chilli-con-carne": "Herbs & Spices",
    "en:canned-coconut-milk": "Dairy and Egg Products",
    "en:durum-wholewheat-semolina": "Breads & Buns",
    "en:mexican-sauce": "Mexican Dinner Mixes",
    "en:taco-kit": "Mexican Dinner Mixes",
    "en:feta-pastries": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:macaroni": "Pasta by Shape & Type",
    "en:mixed-beans": "Legumes and Legume Products",
    "en:sports-drink": "Drinks",
    "en:coca": "Chocolate",
    "en:energy-80": "Coffee",
    "en:chocolate-cupcakes": "Chocolate",
    "en:broths": "Soups, Sauces, and Gravies",
    "en:shortening": "Fats and Oils",
    "en:tamales": "Mexican Dinner Mixes",
    "en:guava-juice": "Drinks",
    "en:potato-snack": "Potato",
    "en:drink-mix": "Drinks",
    "en:syrups": "Jam, Jelly & Fruit Spreads",
    "en:spice-biscuits": "Flours & Corn Meal",
    "en:salsa": "Canned Food",
    "en:grocery-condiments-sauces-mustards": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:non-dairy-beverage": "Drinks",
    "en:meal-kits": "Entrees, Sides & Small Meals",
    "en:groceries": "Branded Food Products Database",
    "en:ground-turkey": "Lamb, Veal, and Game Products",
    "en:popcorn-chicken": "Lamb, Veal, and Game Products",
    "en:fruit-spread": "Jam, Jelly & Fruit Spreads",
    "en:frozen-mix-vegetables": "Vegetable and Lentil Mixes",
    "en:tuna-in-water": "Finfish and Shellfish Products",
    "en:jalepeno": "Vegetables and Vegetable Products",
    "en:oatmel-cereals": "Breakfast Cereals",
    "en:frozen-canadian-wild-bluberries": "Fruits and Fruit Juices",
    "en:frozen-baby-brussels-sprouts": "Vegetables and Vegetable Products",
    "en:vegetarian-bean-chilli": "Legumes and Legume Products",
    "en:frozen-pitted-cherries": "Fruits and Fruit Juices",
    "en:chocolate-covered-wafer-eggs": "Chocolate",
    "en:frozen-potato-onion-perogies": "Potato",
    "en:beef-wieners": "Beef Products",
    "en:bean-burger": "Legumes and Legume Products",
    "en:coffee-cream": "Coffee",
    "en:tuna-snack-pack": "Finfish and Shellfish Products",
    "en:chicken-pot-pie": "Breads & Buns",
    "en:fruit-juice-blend-from-concentrate-with-natural-flavour": "Fruits and Fruit Juices",
    "en:tortilla": "Breads & Buns",
    "en:soft-tortilla": "Breads & Buns",
    "en:chicken-strips": "Poultry Products",
    "en:skim-milk": "Dairy and Egg Products",
    "en:baby-carrots": "Vegetables and Vegetable Products",
    "en:yogurt-dressing-dip": "Yogurt",
    "en:dill-sauce": "Canned Food",
    "en:egg-nog": "Dairy and Egg Products",
    "en:sherbert": "Ice Cream & Frozen Yogurt",
    "en:bruschetta": "Other Deli",
    "en:chicken-and-vegetable-stir-fry": "Entrees, Sides & Small Meals",
    "en:breaded-products": "Entrees, Sides & Small Meals",
    "en:cactus": "Vegetables and Vegetable Products",
    "en:fat-free-milk": "Dairy and Egg Products",
    "en:whole-grain": "Nut and Seed Products",
    "en:corn-dog": "Lamb, Veal, and Game Products",
    "en:pepperoni": "Other Deli",
    "en:tortillas": "Breads & Buns",
    "en:minced-garlic": "Spices and Herbs",
    "en:corn-tortilla": "Breads & Buns",
    "en:snack-nuts": "Nut and Seed Products",
    "en:chicken-tenders": "Poultry Products",
    "en:flavouring-syrup": "Confectionery Products",
    "en:graham-crackers": "Crackers & Biscotti",
    "en:mexican-dinner-mixes": "Mexican Dinner Mixes",
    "en:pita-chips": "Chips, Pretzels & Snacks",
    "en:chocolate-chips": "Chocolate",
    "en:canned-diced-tomatoes": "Fruits and Fruit Juices",
    "en:milk-chocolate-filled-with-caramel": "Dairy and Egg Products",
    "en:purees": "Fruits and Fruit Juices",
    "en:apple-pure": "Fruits and Fruit Juices",
    "en:egg-mayo": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:hard-cider": "Alcoholic Beverages",
    "en:meats": "Other Meats",
    "en:filets-de-poulet": "Poultry Products",
    "en:bread-rolls": "Breads & Buns",
    "en:yellowfin-tuna-wild-caught": "Finfish and Shellfish Products",
    "en:roasted-chicken": "Poultry Products",
    "en:grated-pecorino-romano-cheese": "Dairy and Egg Products",
    "en:green-bean-salad": "Legumes and Legume Products",
    "en:raw-tomatoes": "Fruits and Fruit Juices",
    "en:hot-papers": "Vegetables and Vegetable Products",
    "en:candy-bars": "Chocolate",
    "en:melanges-pour-cocktails": "Alcoholic Beverages",
    "en:buscuits": "Breads & Buns",
    "en:boissons": "Drinks",
    "en:plant-based-breakfast-patties": "Vegetables and Vegetable Products",
    "en:applesauce-portions": "Pre-Packaged Fruit & Vegetables",
    "en:low-sugar-bar": "Chocolate",
    "en:desserts-baking-decorations-frosting": "Confectionery Products",
    "en:potatoes-taters": "Potato",
    "en:premium-cookies": "Sweets",
    "en:is-it-gelatin": "Sweets",
    "en:dried-egg-noodles-with-porchini": "Dairy and Egg Products",
    "en:pizza-bagel": "Pizza Mixes & Other Dry Dinners",
    "en:fruit-and-grain-breakfast-buns": "Breads & Buns",
    "en:pre-sliced-sandwich-buns": "Breads & Buns",
    "en:grain-free-rice": "Rice",
    "en:mango-chunks": "Fruits and Fruit Juices",
    "en:instant-oatmeal": "Breakfast Cereals",
    "en:aliments-et-boissons-a-base-de-vegetaux": "",
    "en:kale": "Vegetables and Vegetable Products",
    "en:green-chili-paste": "Vegetables and Vegetable Products",
    "en:prosciutto": "Other Deli",
    "en:non-dairy-creamer": "Dairy and Egg Products",
    "en:baking-powder": "Flours & Corn Meal",
    "en:roasted-seaweed": "Vegetables and Vegetable Products",
    "en:tea-biscuits": "Crackers & Biscotti",
    "en:dark-chocolate-with-prune-and-white-chocolate": "Chocolate",
    "en:hot-dogs": "Meals, Entrees, and Side Dishes",
    "en:banana-chips": "Vegetables and Vegetable Products",
    "en:rice-cakes": "Rice",
    "en:corn-cakes": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:veggie-crisps": "Vegetables and Vegetable Products",
    "en:vegan-fish-sauce": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:almonds-coaded-in-coconut-and-dark-chocolate": "Chocolate",
    "en:coconut-nectar": "Pre-Packaged Fruit & Vegetables",
    "en:vegan-protein-smoothie-mix": "Dietary Supplements",
    "en:deep-fried": "Fast Foods",
    "en:juice": "Fruits and Fruit Juices",
    "en:cauliflower-rice": "Rice",
    "en:gluten-free-chocolate": "Chocolate",
    "en:energy-gum": "Dietary Supplements",
    "en:vegan-milk": "Dairy and Egg Products",
    "en:fire-tonic-for-metabolic-immune-support": "Dietary Supplements",
    "en:coconut-flour": "Flours & Corn Meal",
    "en:dessert-cookies": "Baking Decorations & Dessert Toppings",
    "en:black-bean-spaghetti": "Legumes and Legume Products",
    "en:semi-soft-surface-ripened-cheese": "Dairy and Egg Products",
    "en:alkaline-water": "Water",
    "en:gouda-cheese": "Dairy and Egg Products",
    "en:seed-oil": "Fats and Oils",
    "en:zero-alcohol-beer": "Drinks",
    "en:pork-product": "Pork Products",
    "en:nutrition-drink": "Dietary Supplements",
    "en:protein-chips": "Dietary Supplements",
    "en:plant-based-milk": "Dairy and Egg Products",
    "en:vitamin-blend": "Dietary Supplements",
    "en:maris-piper-potatoes": "Potato",
    "en:chocolate-and-vanilla-cookies": "Baked Products",
    "en:mooncake": "Baked Products",
    "en:chicken-gravy-granules": "",
    "en:snack-candy": "Soups, Sauces, and Gravies",
    "en:nature": "Vegetables and Vegetable Products",
    "en:sparkling-water-caffeine": "Water",
    "en:schnitzel": "Meals, Entrees, and Side Dishes",
    "en:dried-chili": "Vegetables and Vegetable Products",
    "en:milk-tablet": "Dairy and Egg Products",
    "en:calcium": "Dietary Supplements",
    "en:rice-snacks": "Rice",
    "en:organic-drink": "Drinks",
    "en:chinese-pastry": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:dobrogean-pie": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:immunity-booster": "Dietary Supplements",
    "en:cereal-covered-in-cinnamon": "Cereal",
    "en:proteinpulver": "Dietary Supplements",
    "en:nutritionally-complete-food": "Dietary Supplements",
    "en:pudding-rice": "Rice",
    "en:fish-and-meat-and-eggs": "Entrees, Sides & Small Meals",
    "en:sour-cherries": "Fruits and Fruit Juices",
    "en:chips": "Chips, Pretzels & Snacks",
    "en:cream-cake-vanilla": "Confectionery Products",
    "en:mild-nussig-cheese": "Dairy and Egg Products",
    "en:tinned-fruit": "Fruits and Fruit Juices",
    "en:baked-haricot-beans": "Legumes and Legume Products",
    "en:alcoholic-sparkling-water": "Alcoholic Beverages",
    "en:flapjack": "Breakfast Cereals",
    "en:granola-cereal": "Breakfast Cereals",
    "en:mint-chocolate": "Chocolate",
    "en:ready-to-est-corn": "Flours & Corn Meal",
    "en:soup-paste": "Soups, Sauces, and Gravies",
    "en:vegan-butter": "Fats and Oils",
    "en:rice-sticks": "Rice",
    "en:fresh-soup": "Soups, Sauces, and Gravies",
    "en:energy-powder": "Dietary Supplements",
    "en:caramel-slice": "Jam, Jelly & Fruit Spreads",
    "en:brocoli-soup": "Soups, Sauces, and Gravies",
    "en:instant-rice-pot": "Rice",
    "en:single-cream": "Dairy and Egg Products",
    "en:frozen-sweetcorn": "Frozen Food",
    "en:yorkshire-puddings": "Yogurt",
    "en:soft-drink": "Drinks",
    "en:chicken-breast-fillets": "Poultry Products",
    "en:oven-chips": "Chips, Pretzels & Snacks",
    "en:fishcake": "Finfish and Shellfish Products",
    "en:instant-porridge": "Cereal Grains and Pasta",
    "en:hot-chocolate-sachet": "Chocolate",
    "en:protein-nut-crunch": "Nut and Seed Products",
    "en:frozen-vegaterian-meatballs": "Vegetables and Vegetable Products",
    "en:pistachios-in-shells": "Nut and Seed Products",
    "en:potato-and-rice-snacks": "Rice",
    "en:vegetable-pesto-melts": "Vegetables and Vegetable Products",
    "en:caramel-sauce": "Jam, Jelly & Fruit Spreads",
    "en:sliced-meats": "Other Deli",
    "en:snack-bars": "Snack, Energy & Granola Bars",
    "en:ginger-nut-biscuits": "Snack, Energy & Granola Bars",
    "en:ham-slices": "Pork Products",
    "en:frozen-haddock-fillets": "Finfish and Shellfish Products",
    "en:beef-and-ale-hotpot": "Soups, Sauces, and Gravies",
    "en:nut-roast": "Nut and Seed Products",
    "en:granola-for-breakfast": "Breakfast Cereals",
    "en:potato-croquettes": "Potato",
    "en:ice-cream-salted-caramel": "Ice Cream & Frozen Yogurt",
    "en:fruit-bar": "Snack, Energy & Granola Bars",
    "en:handcooked-potato-crisps": "Potato",
    "en:malted-wheat-sourdough-bread": "Breads & Buns",
    "en:chicken-mince": "Poultry Products",
    "en:yogurts-with-a-fruit-layer": "Yogurt",
    "en:toddler-snack": "Baby Foods",
    "en:chickpea-snack": "Legumes and Legume Products",
    "en:oat-bar": "Nut and Seed Products",
    "en:organic-dark-chocolate": "Chocolate",
    "en:main-course": "Meals, Entrees, and Side Dishes",
    "en:zero-calorie-flavour-drop": "Beverages",
    "en:veggie-mash-cauliflower-and-green-pea": "Vegetables and Vegetable Products",
    "en:sweet-dessert": "Sweets",
    "en:pomergranatesauce": "Fruits and Fruit Juices",
    "en:mocktail": "Drinks",
    "en:wafers-with-hazelnut-cream": "Sweets",
    "en:pepper-paste": "Spices and Herbs",
    "en:chicken-rashers": "Poultry Products",
    "en:vegan-burger": "Vegetables and Vegetable Products",
    "en:frozen-oven-chips": "Chips, Pretzels & Snacks",
    "en:vegan-mayonnaise": "Salad Dressing & Mayonnaise",
    "en:raw-broccoli": "Vegetables and Vegetable Products",
    "en:belgian-chocolate": "Chocolate",
    "en:milk-fresh-semi-skimmed": "Dairy and Egg Products",
    "en:cold-cuts-made-with-chicken": "Poultry Products",
    "en:white-cheese": "Dairy and Egg Products",
    "en:cornflakes": "Breakfast Cereals",
    "en:protein-cookie": "Dietary Supplements",
    "en:semolina": "Flours & Corn Meal",
    "en:aspics": "Spices and Herbs",
    "en:vacuum-packed-steamed-beets": "Vegetables and Vegetable Products",
    "en:dried-beans": "Legumes and Legume Products",
    "en:fruit-puree": "Fruits and Fruit Juices",
    "en:banana-chocolate-bar": "Chocolate",
    "en:roasted-corn": "Vegetables and Vegetable Products",
    "en:greek-style-ogurt": "Yogurt",
    "en:additive-free-ready-made-food": "Entrees, Sides & Small Meals",
    "en:breakfast-cereals-biscuit": "Cereal",
    "en:effervescent-hydration-electrolyte-tablets": "Dietary Supplements",
    "en:ice-cream-mix": "Ice Cream & Frozen Yogurt",
    "en:yaourt": "Ice Cream & Frozen Yogurt",
    "en:chocolat": "Chocolate",
    "en:high-protein-soluble-product-with-slow-calories": "Dietary Supplements",
    "en:snacks-sweet-snacks-biscuits-and-cakes-biscuits-chocolate-cakes": "Sweets",
    "en:butter-biscuit-cookie-with-chocolate": "Chocolate",
    "en:wheat-biscuits-covered-with-dark-chocolate": "Chocolate",
    "en:chocolate-coated-biscuit": "Chocolate",
    "en:hot-spicy-crisps": "Chips, Pretzels & Snacks",
    "en:functional-cookies": "Confectionery Products",
    "en:protein-snacks": "Dietary Supplements",
    "en:sugar-free-chocolates": "Chocolate",
    "en:weight-loss": "Dietary Supplements",
    "en:bee-products": "Jam, Jelly & Fruit Spreads",
    "en:gummy-raspberries": "Vegetables and Vegetable Products",
    "en:deshydrated-fruit": "Fruits and Fruit Juices",
    "en:whole-wheat-bread": "Breads & Buns",
    "en:palegg": "Dairy and Egg Products",
    "en:digestive-biscuit": "Crackers & Biscotti",
    "en:suger": "Branded Food Products Database",
    "en:hard-bread": "Breads & Buns",
    "en:potato-mash-mix": "Potato",
    "en:cod-caviar": "Finfish and Shellfish Products",
    "en:sesame-crackers": "Crackers & Biscotti",
    "en:ice-tea-peach": "Drinks",
    "en:drink-yogurt": "Yogurt",
    "en:chesse": "Dairy and Egg Products",
    "en:crema-de-leche": "Dairy and Egg Products",
    "en:papas-fritas": "Fast Foods",
    "en:refresco-de-cola": "Drinks",
    "en:sparkling-mineral-water": "Drinks",
    "en:oil": "Fats and Oils",
    "en:chamoy": "Spices and Herbs",
    "en:galletas": "Cookies",
    "en:sugar-free-candy": "Sweets",
    "en:malt-chocolate-powdered-milk-drink": "Chocolate",
    "en:pizza-pollo": "Pizza Mixes & Other Dry Dinners",
    "en:frozen-cheesecakes": "Sweets",
    "en:biscuits-aux-fruits": "Crackers & Biscotti",
    "en:instant-iced-tea-apple-flavor": "Drinks",
    "en:condimentos": "Salad Dressing & Mayonnaise",
    "en:cacao-natural": "Chocolate",
    "en:tomate-triturado": "Fruits and Fruit Juices",
    "en:plant-based-bugers": "Other Meats",
    "en:biscoito": "Crackers & Biscotti",
    "en:pastel-dough": "Flours & Corn Meal",
    "en:diced-tomato": "Fruits and Fruit Juices",
    "en:choco-filled-crackers": "Cookies",
    "en:gluten-free-tortillas": "Breads & Buns",
    "en:pasteurized-yogurt": "Yogurt",
    "en:dark-chocolate-bar-with-coconut": "Chocolate",
    "en:chocolate-turron-with-hazelnuts": "Chocolate",
    "en:chocolate-toffee": "Chocolate",
    "en:huevos": "Dairy and Egg Products",
    "en:vegetarian-pasta": "Cereal Grains and Pasta",
    "en:acidophilic-milk": "Dairy and Egg Products",
    "en:dumplings": "Entrees, Sides & Small Meals",
    "en:minced-flax": "Nut and Seed Products",
    "en:chicken-franks": "Poultry Products",
    "en:oat-cookie-filled-with-vanilla-cream": "Cookies",
    "en:multivitamine": "Dietary Supplements",
    "en:chicken-stock": "Soups, Sauces, and Gravies",
    "en:soup-base": "Soups, Sauces, and Gravies",
    "en:coffeecreamers": "Coffee",
    "en:plant-based-fish": "Finfish and Shellfish Products",
    "en:spread-not-butter": "Fats and Oils",
    "en:sliced-cooked-ham": "Pork Products",
    "en:dry-fruit": "Fruits and Fruit Juices",
    "en:quinoa-bar": "Snack, Energy & Granola Bars",
    "en:frozen-prawns": "Finfish and Shellfish Products",
    "en:chicken-parmigiana": "Poultry Products",
    "en:chicken-corn-chowder": "Poultry Products",
    "en:gluten-free-crisp-rice-cereal": "Rice",
    "en:roasted-corn-kernels": "Vegetables and Vegetable Products",
    "en:desserts-semoule-caramel": "Sweets",
    "en:blueberry-jam": "Jam, Jelly & Fruit Spreads",
    "en:skewers": "Meals, Entrees, and Side Dishes",
    "en:pure-grapefruit-juice": "Fruits and Fruit Juices",
    "en:biscuits-et-gateaux": "Crackers & Biscotti",
    "en:biscuits-aperitifs": "Crackers & Biscotti",
    "en:ravioli-au-fromage": "Pasta by Shape & Type",
    "en:oeufs": "Dairy and Egg Products",
    "en:charcuterie": "Dairy and Egg Products",
    "en:biscuits-vegan": "Crackers & Biscotti",
    "en:ice-cream-raspberry": "Ice Cream & Frozen Yogurt",
    "en:filled-salted-sticks-with-peanut": "Nut and Seed Products",
    "en:pate-spreads-meat-spread-meat-product": "Other Meats",
    "en:sparkling-drink": "Drinks",
    "en:chicken-pate": "Poultry Products",
    "en:biscuits-fourres": "Crackers & Biscotti",
    "en:beef-mince": "Beef Products",
    "en:juices": "Fruits and Fruit Juices",
    "en:chips-und-pommes-frites": "Potato",
    "en:street-food": "Entrees, Sides & Small Meals",
    "en:mayonnaise-ohne-eier": "Salad Dressing & Mayonnaise",
    "en:vanilla-pudding": "Dairy and Egg Products",
    "en:rice-cake": "Rice",
    "en:chocolate-biscuit-bar": "Chocolate",
    "en:tinned-tomatoes": "Other Cooking Sauces",
    "en:mackerel-fillets-in-tomato-sauce": "Other Cooking Sauces",
    "en:pie-chicken-ham": "Other Meats",
    "en:frozen-peas": "Legumes and Legume Products",
    "en:dried-fruit-and-nut-mix": "Nut and Seed Products",
    "en:yorkshire-pudding": "Dairy and Egg Products",
    "en:hot-chocolate": "Chocolate",
    "en:1-low-fat-milk-with-added-milk-protein": "Dairy and Egg Products",
    "en:sndwiches": "Meals, Entrees, and Side Dishes",
    "en:chocolate-block": "Chocolate",
    "en:white-hot-chocolate": "Chocolate",
    "en:salad-kit": "Vegetable and Lentil Mixes",
    "en:meatless-hot-dogs": "Meals, Entrees, and Side Dishes",
    "en:light-ice-cream": "Ice Cream & Frozen Yogurt",
    "en:sugar-cone": "Ice Cream & Frozen Yogurt",
    "en:ham-sandwich-meat": "Pork Products",
    "en:whole-wheat-gnocchi": "Potato",
    "en:peppers-in-vinegar": "Pickles, Olives, Peppers & Relishes",
    "en:lunch-meat": "Other Deli",
    "en:black-bean-chips": "Legumes and Legume Products",
    "en:sweet-breakfast-cereals": "Breakfast Cereals",
    "en:sweet-breakfast-cereals-fortified-with-vitamins-and-chemical-elements": "Breakfast Cereals",
    "en:french-fries": "Fast Foods",
    "en:refrigerated-foods": "Frozen Food",
    "en:meat-dishes": "Other Meats",
    "en:vegetable-smoothie": "Vegetables and Vegetable Products",
    "en:vanilla-ice": "Frozen Food",
    "en:coconut-flakes": "Fruits and Fruit Juices",
    "en:soup-mix": "Soups, Sauces, and Gravies",
    "en:chocolate-covered-confectionery": "Chocolate",
    "en:ready-to-drink-iced-coffee": "Coffee",
    "en:nacho-cheese-flavor": "Cheese",
    "en:seasoning-mix": "Seasoning Mixes, Salts, Marinades & Tenderizers",
    "en:potato-biscuits": "Potato",
    "en:chocolate-ice-cream-with-marshmallow-and-peanuts": "Chocolate",
    "en:dark-chocolate-wafers-rolls": "Chocolate",
    "en:fruit-flavored-jellies": "Jam, Jelly & Fruit Spreads",
    "en:white-choco-filled-churos": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:toaste-breads": "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "en:coffee-mix": "Coffee",
    "en:sugar-free-instant-ice-teas": "Drinks",
    "en:chinese-bread": "Breads & Buns",
    "en:sweetened-peanut-butter": "Jam, Jelly & Fruit Spreads",
    "en:enhaned-water": "Water",
    "en:orange-flavored-ice-tea": "Fruits and Fruit Juices",
    "en:chocolate-milk-with-peanuts": "Dairy and Egg Products",
    "en:sugar-free-coffee": "Coffee",
    "en:carbonated-orange-flavored-drink": "Drinks",
    "en:sweetened-biscuits": "Crackers & Biscotti",
    "en:powdered-soups": "Soups, Sauces, and Gravies",
    "en:pork-jerky": "Pork Products",
    "en:dried-fish": "Finfish and Shellfish Products",
    "en:curry": "Soups, Sauces, and Gravies",
    "en:beef-curry": "Soups, Sauces, and Gravies",
    "en:biscuit-stick": "Crackers & Biscotti",
    "en:biscuit-filled-with-coffee-cream": "Crackers & Biscotti",
    "en:soybean": "Legumes and Legume Products",
    "en:potato-waffle": "Potato",
    "en:chicken-pie": "Poultry Products",
    "en:fried-chicken": "Poultry Products",
    "en:canned-pear": "Canned Fruit",
    "en:carbonated-soda-water": "Drinks",
    "en:tomato-and-basil-soup": "Soups, Sauces, and Gravies",
    "en:tomato-concentrate": "Other Cooking Sauces",
    "en:porridge-oats": "Breakfast Cereals",
    "en:tinned-salmon": "Finfish and Shellfish Products",
    "en:couscous-salad": "Vegetable and Lentil Mixes",
    "en:minced-white-fish": "Finfish and Shellfish Products",
    "en:shortcake": "Sweets",
    "en:icing": "Sweets",
    "en:beef-gravy-granules": "Soups, Sauces, and Gravies",
    "en:taco": "Mexican Dinner Mixes",
    "en:beef-soups": "Soups, Sauces, and Gravies",
    "en:rice-packets": "Rice",
    "en:canned-prunes": "Canned Fruit",
    "en:omlette": "Egg",
    "en:ginger-paste": "Spices and Herbs",
    "en:fish-cakes": "Finfish and Shellfish Products",
    "en:salted-soybean": "Legumes and Legume Products",
    "en:tom-yum-paste": "Jam, Jelly & Fruit Spreads",
    "en:chocolate-drinks": "Chocolate",
    "en:artificial-cream": "Dairy and Egg Products",
    "en:rice-crisp": "Rice",
    "en:fish-snack": "Finfish and Shellfish Products",
    "en:shrimp-paste": "Finfish and Shellfish Products",
    "en:sweetened-condensed-milk": "Dairy and Egg Products",
    "en:electrolyte-drink": "Dietary Supplements",
    "en:sardines-in-chili-sauce": "Finfish and Shellfish Products",
    "en:pork-and-chicken-products": "Other Meats",
    "en:chocolate-drink": "Chocolate",
    "en:chocolate-chip-butter-cookies": "Chocolate",
    "en:chou-pastry-filled-with-chocolate": "Chocolate",
    "en:chili-paste": "Spices and Herbs",
    "en:durian-products": "Fruits and Fruit Juices",
    "en:fish-product": "Finfish and Shellfish Products",
    "en:noodles-with-shrimps": "Finfish and Shellfish Products",
    "en:fish-products": "Finfish and Shellfish Products",
    "en:soy-meat": "Vegetables and Vegetable Products",
    "en:mixed-berry-juices": "Fruits and Fruit Juices",
    "en:mixed-berry-juice": "Fruits and Fruit Juices",
    "en:rice-noodles": "Rice",
    "en:mixed-berries-juice": "Fruits and Fruit Juices",
    "en:tamarind-candy": "Fruits and Fruit Juices",
    "en:grilled-chicken-with-sticky-rice": "Poultry Products",
    "en:fried-noodle": "Cereal Grains and Pasta",
    "en:salad": "Vegetable and Lentil Mixes",
    "en:grilled-pork": "Pork Products",
    "en:meals-with-pork": "Pork Products",
    "en:coffee-cakes": "Coffee",
    "en:soft-cake": "Sweets",
    "en:vegetarians": "Vegetables and Vegetable Products",
    "en:rice-porridge": "Rice",
    "en:soybean-paste": "Legumes and Legume Products",
    "en:desserts-frozen-foods-frozen-desserts-ice-creams-and-sorbets-ice-creams": "Ice Cream & Frozen Yogurt",
    "en:seasoning-sauce": "Seasoning Mixes, Salts, Marinades & Tenderizers",
    "en:supplements": "Dietary Supplements",
    "en:salmon-ball": "Finfish and Shellfish Products",
    "en:sesame-soy-sauce": "Seasoning Mixes, Salts, Marinades & Tenderizers",
    "en:salads-with-chicken": "Vegetable and Lentil Mixes",
    "en:salad-with-tuna": "Vegetable and Lentil Mixes",
    "en:roasted-broad-beans": "Legumes and Legume Products",
    "en:pork-products": "Pork Products",
    "en:raspberries-juice": "Fruits and Fruit Juices",
    "en:chilli-paste": "Pickles, Olives, Peppers & Relishes",
    "en:favored-milk": "Dairy and Egg Products",
    "en:rambutan-in-heavy-syrup": "Fruits and Fruit Juices",
    "en:coconut-juices": "Fruits and Fruit Juices",
    "en:pickled-green-mustard": "Ketchup, Mustard, BBQ & Cheese Sauce",
    "en:meals-with-crab": "Finfish and Shellfish Products",
    "en:macaroni-with-chicken-and-sausage": "Cereal Grains and Pasta",
    "en:durian-crisp": "Fruits and Fruit Juices",
    "en:caffein-drink": "Coffee",
    "en:kelp-noodle": "Cereal Grains and Pasta",
    "en:tamarind": "Fruits and Fruit Juices",
    "en:dried-lemon": "Fruits and Fruit Juices",
    "en:defatted-soy-flour": "Flours & Corn Meal",
    "en:tamarind-drink": "Fruits and Fruit Juices",
    "en:beverages-with-blueberry": "Fruits and Fruit Juices",
    "en:pistachios-puree": "Nut and Seed Products",
    "en:salted-plum": "Fruits and Fruit Juices",
    "en:pickled-radish": "Pickles, Olives, Peppers & Relishes",
    "en:bean": "Legumes and Legume Products",
    "en:streamed-egg": "Egg",
    "en:mungbean-noodle": "Cereal Grains and Pasta",
    "en:meals-with-porks": "Pork Products",
    "en:crab-product": "Finfish and Shellfish Products",
    "en:grain-bar": "Snack, Energy & Granola Bars",
    "en:tomato": "Fruits and Fruit Juices",
    "en:brownie-stick": "Snack, Energy & Granola Bars",
    "en:wholegrain": "Breads & Buns",
    "en:butter-toast": "Breads & Buns",
    "en:white-eggs": "Egg",
    "en:bologna": "Other Deli",
    "en:vegetarian-meat-paste-with-sticky-rice": "",
    "en:milk-tea": "Dairy and Egg Products",
    "en:durian-juice": "Fruits and Fruit Juices",
    "en:soymilk-products": "Dairy and Egg Products",
    "en:pork-lasagne-with-cheese": "Cheese",
    "en:spinach-cheese-bake": "Cheese",
    "en:sandwich-tuna": "Finfish and Shellfish Products",
    "en:cheese-products": "Cheese",
    "en:durian": "Fruits and Fruit Juices",
    "en:crepe-cake": "Sweets",
    "en:fish-balls": "Finfish and Shellfish Products",
    "en:fish-ball": "Finfish and Shellfish Products",
    "en:dried-octopus": "Finfish and Shellfish Products",
    "en:cake-rolls": "Sweets",
    "en:yogurt-milk": "Yogurt",
    "en:instant-tea": "Drinks",
    "en:fermented-rice": "Rice",
    "en:mix-berry-juice": "Fruits and Fruit Juices",
    "en:crispy-pumpkin": "Vegetables and Vegetable Products",
    "en:sandwich-high-protein": "Meals, Entrees, and Side Dishes",
    "en:potato": "Potato",
    "en:banana-products": "Fruits and Fruit Juices",
    "en:salmon-products": "Finfish and Shellfish Products",
    "en:milk-chocolate-filled-biscuits": "Chocolate",
    "en:soft-pie-filled-with-chocolate": "Chocolate",
    "en:instant-noodles-with-seasoning": "Prepared Pasta & Pizza Sauces",
    "en:flavoured-sandwich-biscuits": "Crackers & Biscotti",
    "en:palak-paneer": "Pickles, Olives, Peppers & Relishes",
    "en:chickpea-masala": "Legumes and Legume Products",
    "en:milk-chocolate-with-vanilla-flavored-cream-and-oreo-tidbits": "Chocolate",
    "en:amul-dark-chocolate": "Chocolate",
    "en:soft-drinks": "Soda",
    "en:buscuit": "Crackers & Biscotti",
    "en:indian-snacks": "Other Snacks",
    "en:fried-snack": "Fast Foods",
    "en:puffed-rice-blend": "Rice",
    "en:sweets-desserts": "Sweets",
    "en:fried-soy-sticks": "Fast Foods",
    "en:full-cream-milk": "Dairy and Egg Products",
    "en:nut-crackers": "Nut and Seed Products",
    "en:toned-milk": "Dairy and Egg Products",
    "en:herbal": "Coffee",
    "en:cookie-cake": "Cookies",
    "en:pickle-mango": "Fruits and Fruit Juices",
    "en:mixed-fruits-and-vegetables-pickel": "Fruits and Fruit Juices",
    "en:spicy-potato-noodle-snack": "Potato",
    "en:milk-curds": "Dairy and Egg Products",
    "en:mini-wafer-filled-with-choco-cream": "Chocolate",
    "en:eggless-mayonnaise": "Salad Dressing & Mayonnaise",
    "en:fried-cereal-snack": "Breakfast Cereals",
    "en:soft-chocolate-cookies-with-melted-choco-inside": "Chocolate",
    "en:iced-teas-with-apple-flavor": "Fruits and Fruit Juices",
    "en:bread-roll": "Breads & Buns",
    "en:fruit-toast": "Fruits and Fruit Juices",
    "en:laits": "Dairy and Egg Products",
    "en:formulated-supplementary-food": "Dietary Supplements",
    "en:chinese-hokkien-noodles": "Entrees, Sides & Small Meals",
    "en:fruit-drinks": "Fruits and Fruit Juices",
    "en:chicken-snacks": "Poultry Products",
    "en:alcohol-free-ginger-drink": "Drinks",
    "en:apricot-fruit-bar": "Fruits and Fruit Juices",
    "en:mct-oil": "Fats and Oils",
    "en:gluten-free-whole-grain-bites": "Cereal Grains and Pasta",
    "en:plant-based-foods-and-beverages-plant-based-foods-legumes-and-their-products-snacks-products-without-gluten": "Legumes and Legume Products",
    "en:oat-bars": "Breakfast Cereals",
    "en:frozen-asian-food": "Frozen Food",
    "en:fruit-snack": "Fruits and Fruit Juices",
    "en:vegan-chocolate": "Chocolate",
    "en:meat-paste": "Other Meats",
    "en:vegan-cake": "Sweets",
    "en:sustenance-bar": "Snack, Energy & Granola Bars",
    "en:bun-filled-with-buttercream": "Confectionery Products",
    "en:instant-oats": "Breakfast Cereals",
    "en:premix-coffee": "Coffee",
    "en:canned-navy-bean": "Legumes and Legume Products",
    "en:roasted-almond": "Nut and Seed Products",
    "en:powders": "Dietary Supplements"
}